export const Worker = {
  raw: {
    total: 1,
    max_score: 1,
    hits: [
      {
        _index: 'people',
        _type: 'worker',
        _id: '10706728',
        _score: 1,
        _source: {
          RootPersonRoleTypeCd: 'EMP',
          FirstNm: 'Joshua',
          MiddleInitialTxt: 'J',
          LastNm: 'Harrison',
          FullNm: 'Harrison, Joshua J',
          AuthenticationDomain: 'amr',
          Idsid: 'jjharris',
          MailStopTxt: 'RA1-333',
          CorporateEmailTxt: 'joshua.j.harrison@intel.com',
          WorkPhoneNbr: '+1 (916) 377 5222',
          MobilePhoneNbr: null,
          WorkPhoneFaxNbr: null,
          WorkPhonePagerNbr: null,
          AssistantContactTxt: '+1 (916) 356 9268',
          WorkLocationTxt: 'RA1',
          WorkLocationBuildingCd: 'RA1',
          TimeZoneCd: 'PST   ',
          EmployeeStatusCd: 'A',
          EmployeeClassCd: 'R',
          EmploymentTypeCd: 'S',
          JobTypeCd: '200082',
          JobTypeNm: 'Application Developer',
          JobFamilyCd: 'Tech',
          DepartmentCd: '34396',
          ManagerWwid: '10062376',
          ManagerNm: 'Don Meyers',
          CostCenterCd: '40300',
          WWID: '10706728',
        },
      }
    ],
  },
  clean: {
    FirstNm: 'Joshua',
    LastNm: 'Harrison',
    CorporateEmailTxt: 'joshua.j.harrison@intel.com',
    JobTypeNm: 'Application Developer',
    WorkPhoneNbr: '+1 (916) 377 5222',
    WWID: '10706728',
  }
};
