export const Worker = {
  raw: [
    {
      $id: '1',
      AcquisitionCompanyNm: null,
      AssignmentActiveInd: 'N',
      AssignmentDepartmentCd: null,
      AssignmentDepartmentNm: null,
      AssignmentDestinationBuildingCd: null,
      AssignmentDestinationBuildingNm: null,
      AssignmentDestinationCountryCd: null,
      AssignmentDestinationCountryNm: null,
      AssignmentDestinationCountrySubdivisionCd: null,
      AssignmentDestinationCountrySubdivisionNm: null,
      AssignmentDestinationGeographyCd: null,
      AssignmentDestinationSiteCd: null,
      AssignmentDestinationSiteNm: null,
      AssignmentDestinationSubgeographyCd: null,
      AssignmentEndDt: '',
      AssignmentHRBusinessPartnerNm: null,
      AssignmentHRBusinessPartnerWwid: null,
      AssignmentLengthTypeCd: null,
      AssignmentManagerNm: null,
      AssignmentManagerWwid: null,
      AssignmentOriginBuildingCd: null,
      AssignmentOriginBuildingNm: null,
      AssignmentOriginCountryCd: null,
      AssignmentOriginCountryNm: null,
      AssignmentOriginCountrySubdivisionCd: null,
      AssignmentOriginCountrySubdivisionNm: null,
      AssignmentOriginGeographyCd: null,
      AssignmentOriginSiteCd: null,
      AssignmentOriginSiteNm: null,
      AssignmentOriginSubgeographyCd: null,
      AssignmentStartDt: '',
      AssistantContactTxt: '+1 (916) 356 9268',
      AuthenticationDomain: 'amr',
      CcMailNm: 'Harrison, Joshua J',
      CompanyCd: '100',
      CompanyCountryCd: 'USA',
      CompanySeniorityDt: 'January 09 2006',
      CorporateEmailTxt: 'joshua.j.harrison@intel.com',
      CostCenterCd: '40300',
      CostCenterNm: 'IT DevOps US',
      DepartmentCd: '34396',
      DepartmentNm: 'Development Methods & Assets',
      DepartmentStartDt: 'June 01 2017',
      DirectLaborInd: 'N',
      EmployeeClassCd: 'R',
      EmployeeStatusCd: 'A',
      EmploymentTypeCd: 'S',
      ExportCountryGroupDsc: 'US Person',
      ExportCountryStatusCd: 'U',
      FirstNm: 'Joshua',
      FullNm: 'Joshua Harrison',
      GeneralLedgerCompanyCd: '100',
      GeographyCd: 'AMER',
      HRBusinessPartnerNm: 'Mikel Bookwalter',
      HRBusinessPartnerWwid: '11572362',
      Idsid: 'jjharris',
      JobTrackNm: 'Tech',
      JobTypeCd: '200082',
      JobTypeNm: 'Application Developer',
      LastNm: 'Harrison',
      LegalFirstNm: 'Joshua',
      LegalFullNm: 'Joshua Harrison',
      LegalLastNm: 'Harrison',
      LegalMiddleInitialTxt: 'J',
      LegalNmInitialsTxt: 'JJH',
      MailStopTxt: 'RA1-333',
      ManagerInd: 'N',
      MiddleInitialTxt: 'J',
      MobilePhoneNbr: null,
      NextLevelCorporateEmailTxt: 'don.meyers@intel.com',
      NextLevelNm: 'Don Meyers',
      NextLevelTypeCd: 'MANAGER',
      NextLevelWwid: '10062376',
      OfficeLocation: 'RA1-FL3-C14',
      RegulatoryCountryCd: 'USA',
      RootPersonRoleTypeCd: 'EMP',
      SabbaticalEndDt: 'July 17 2017',
      SabbaticalStartDt: 'June 20 2017',
      SubgeographyCd: 'NAMR      ',
      SupplierDsc: null,
      TimeZoneCd: 'PST   ',
      WorkInetNbr: '3775222',
      WorkLocationBuildingCd: 'RA1',
      WorkLocationBuildingNm: 'Ronler Acres 1',
      WorkLocationCampusCd: 'RA  ',
      WorkLocationCountryNm: 'United States',
      WorkLocationCountrySubdivisionCd: 'OR',
      WorkLocationSiteCd: 'OR ',
      WorkLocationSiteNm: 'Oregon, Hillsboro                       ',
      WorkPhoneFaxNbr: null,
      WorkPhoneNbr: '+1 (916) 377 5222',
      WorkPhonePagerNbr: null,
      WorkShiftCd: 'USA_1',
      WWID: '10706728'
    }
  ],
  clean: {
    FirstNm: 'Joshua',
    LastNm: 'Harrison',
    CorporateEmailTxt: 'joshua.j.harrison@intel.com',
    JobTypeNm: 'Application Developer',
    WorkPhoneNbr: '+1 (916) 377 5222',
    OfficeLocation: 'RA1-FL3-C14',
    DepartmentNm: 'Development Methods & Assets',
    WWID: '10706728',
  }
};
